#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import SwapTransition kivy.uix.screenmanager.SwapTransition
#:import WipeTransition kivy.uix.screenmanager.WipeTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import RiseInTransition kivy.uix.screenmanager.RiseInTransition
#:import FallOutTransition kivy.uix.screenmanager.FallOutTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition

#Propiedades para las titulos  
<Titulo@Label>
    markup: True
    #font_name: 'snap____.ttf' 
    font_size: 35        
    size_hint:(None, None)
    size:(100, 44)
    pos_hint:{'center_x': .5 , 'center_y': .90}
# Agregamos cada oferta academica que contendra las propiedades basicas
<Add_Oferta@Button>
	markup: True
	#font_name: 'britanic.ttf'
    pos_hint:{'center_x': .5,'center_y': .7}
    size_hint:(.75, .10)
#Reutilizan Butones y dando un nombre 
<Add_Facultad@Add_Oferta>
	size:(250, 50)
    size_hint:(None, None)
    #font_name: 'britanic.ttf'
#heredamos todos los atributos y solo cambiamos el text 
<Add_Carrera@Add_Oferta>
	size:(250, 50)
	markup: True
    multiline: True 
    #font_name: 'britanic.ttf'
    size_hint:(None, None)      
#Declaracion  ventana de Facultades
<Facultades@Screen>
#Declaracion de Maestrias
<Maestrias@Screen>
 #Declaracion de Carreras
<Carreras@Screen>
# Esquemas de los label que llevan los nombre ej Resolucion, Carrera
<TextoInfo@Label> 
    font_size: 25             
    size_hint:(.30, None)
    size:(100, 70)
    pos_hint:{'right_top': .10,'center_y': .75}
#Esquema des los Textinput que sera donde se va a mostarar la carrera
<ResultadoInfo@TextInput>
    size_hint:(.70, None)
    size:(100, 70)
    pos_hint:{'center_x': .60,'center_y': .75}
    disabled: True  
<Boton_Atras@Button>
    text: '[b]ATRAS[/b]'
    markup: True
    #font_name: 'britanic.ttf'
    size_hint:(None, None)
    size:(150, 30)
    pos_hint:{'center_x': .25,'center_y': .05}
<Boton_Siguiente@Button>
    text: '[b]MENU PRINCIPAL[/b]'
    markup: True
    #font_name: 'britanic.ttf'
    size_hint:(None, None)
    size:(150, 30)
    pos_hint:{'center_x': .75,'center_y': .05}    
# Nos servira para mandarle la imagen de plan de estudios de la carrea
<Plan@AsyncImage>
    size: self.size
    size: self.texture_size
# Agregamos la imagen de Plan y la ingresamos en Widget que se pueda mover
<PlanDeEstudio@Screen>
    Widget: 
        Scatter:
            size_hint: None, None
            size: image.size
            Plan:
                id: image   
<Ventanas>:
    titulo: " "
    resolucion: " "
    duracion:" "
    sede: " " 
    horario: " "
    modalidad: " " 
    requerimiento:"0.jpeg" 
    plan:"0.jpeg"
    nombreVentana:"principal"  # para regresar una ventana cuando este en Carreras
    Screen: #Principal
        name: "principal"
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                # source: 'data/logouipapp.png' #se le agrega un imagen como fondo
                source: 'data/fondo.jpg'
        # Titulo: # se agrega el Titulo principal
        #     text:('[b]Principal[/b]')
        # Botones Para Oferta Academica
        Image:
            size_hint: None, None
            size:(300, 100)
            pos_hint:{'center_x': .5,'center_y': .90}
            source: 'data/logo-uip.jpg'
        Titulo:
            text:('[b]OFERTA ACADEMICA[/b]')
            font_size: 50
            pos_hint:{'center_x': .5 , 'center_y': .70}
        Add_Oferta: 
            font_size: 35                 
            text:('[b]LICENCIATURAS[/b]') # se le agrega el titulo al boton  
            #background_color: (0, 0, 255, 0.5)        
            pos_hint:{'center_x': .5,'center_y': .50}
            on_press: 
                root.current=('licenciatura')
                root.transition = RiseInTransition()
        Add_Oferta:
            font_size: 30
            text:('[b]LICENCIATURAS PARA EJECUTIVOS[/b]')
           # color: (0, 0, 255/255, 0.9)
          #  background_color: (255,255,255, 0.9)
            pos_hint:{'center_x': .5,'center_y': .40}
            on_press:
                root.current=('licenciaturaPro') 
                root.transition = FallOutTransition()
        Add_Oferta:
            font_size: 35
            text:('[b]MAESTRIAS Y POSTGRADOS[/b]')
           # background_color: (0, 0, 255, 0.5)
            pos_hint:{'center_x': .5,'center_y': .30}
            on_press: 
                root.current=('maestria_y_postgrado') 
                root.transition = FadeTransition() 
        Image:
            size_hint: None, None
            size:(200, 50)
            source: 'data/kivy.jpg'
    Screen: #Licenciatura
        name: 'licenciatura'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size 
                source: 'data/uip.jpg'       
        Titulo:
            text:
                ('[b]LICENCIATURAS[/b]')
            color: (0, 0, 150/255, 1)
            font_size: 50
        Add_Facultad:
            text: '[b]ARQUITECTURA[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .78}
            on_press: root.current = 'arquitectura'
        Add_Facultad:
            text: '[b]CIENCIAS ADMINISTRATIVAS[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .68}
            on_press: root.current = 'cienciasAdministrativas'
        Add_Facultad:
            text: '[b]CIENCIAS DE LA SALUD[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .58}
            on_press: root.current = 'salud'
        Add_Facultad:
            text: '[b]DERECHO[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .48}
            on_press: root.current = 'derecho'
        Add_Facultad:
            text: '[b]GASTRONOMIA, HOTELERIA Y TURISMO[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .38}
            on_press: root.current = 'gastronomia'
        Add_Facultad:
            text: '[b]INGENIERIA Y SISTEMAS[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .28}
            on_press: root.current = 'ingsistemas'
        Add_Facultad:
            text: '[b]MARITIMA Y PORTUARIA[/b]'
            size: (300, 50)
            background_color: (0, 0, 181/255, 0.7)
            pos_hint:{'center_x': .5,'center_y': .18}
            on_press: root.current = 'maritima'
		Boton_Atras:
			background_color: (0, 0, 181/255, 0.7)
		    pos_hint:{'center_x': .5,'center_y': .07}    
            on_press: root.current = "principal" 
    Screen: #LicenciaturaPro
        name: 'licenciaturaPro'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/ejec.jpg'
        Titulo:
            text:
                ('[b][color=#CB6900]LICENCIATURAS  PARA EJECUTIVOS[/b]')
        Add_Carrera:
            text:'[b]LICENCIATURA EN MERCADEO Y PUBLICIDAD'
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .78}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CTF-24-2014, del 28 de abril de 2014")
                root.carrera()
        Add_Carrera:
            text:'[b]LICENCIATURA EN CONTABILIDAD'
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .68}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CTF-127-2012 de 12 de noviembre de 2012")
                root.carrera() 
        Add_Carrera:
            text:'[b]LICENCIATURA EN COMERCIO INTERNACIONAL'
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .58}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CTF-115-2011, del 27 de diciembre de 2011")
                root.carrera()
        Add_Carrera:
            text:'[b]LICENCIATURA EN BANCA Y FINANZAS'
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .48}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CTF-224-2011, del 27 de abril de 2011")
                root.carrera()
        Add_Carrera:
            text:'[b]   LICENCIATURA EN INGENIERIA\n DE SISTEMAS COMPUTACIONALES'
            multiline: True
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .38}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CACAD-R-03-2009, del 05 de junio de 2009 I Sede: Panama")
                root.carrera()
        Add_Carrera:
            text:'[b]LICENCIATURA EN ADMINISTRACION\n            DE RECURSOS HUMANOS'
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .28}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CTF-195-2011, del 27 de diciembre de 2011")
                root.carrera()
        Add_Carrera:
            text:'[b]           LICENCIATURA EN\nADMINISTRACION DE NEGOCIOS'
            background_color: (1, 128/255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .18}
            size:(400, 50)
            on_press: 
                root.current=('carreras')
                root.datos('licenciaturaPro',"CTF-124-2012, del 12 de noviembre de 2012")
                root.carrera()
        Boton_Atras:  
        	background_color: (1, 128/255, 0, 0.8)
        	pos_hint:{'center_x': .5,'center_y': .07}         
            on_press: root.current = "principal"
    Screen: #Maestria y Postgrados
        name: 'maestria_y_postgrado'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/preparate_mejores_profesores_maestria1.jpg'
        Titulo:
            text:
                ('[b]MAESTRIAS[/b]')
            pos_hint:{'center_x': .30 , 'center_y': .90}
        Add_Facultad:
            text:('[b][color=#000000]EMPRESARIALES')
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .30,'center_y': .75}
            on_press: root.current =('empresarialesmaestria')
        Add_Facultad:
            text:'[b][color=#000000]INNOVACION Y LOGISTICA'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .30,'center_y': .65} 
            on_press: root.current=('innovacionmaestria')           
        Add_Facultad:
            text:'[b][color=#000000]EDUCACION'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .30,'center_y': .55}
            on_press: root.current=('educacionmaestria')
        Add_Facultad:
            text:'[b][color=#000000]DERECHO'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .30,'center_y': .45}
            on_press: root.current=('derechomaestria')
        Add_Facultad:
            text:'[b][color=#000000]SISTEMA DE INFORMACION'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .30,'center_y': .35}
            on_press: root.current=('sistemaimaestria')
        Add_Facultad:
            text:'[b][color=#000000]SALUD'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .30,'center_y': .25}
            on_press: root.current=('saludmaestria')
        Titulo:
            text:
                ('[b]POSTGRADOS[/b]')
            pos_hint:{'center_x': .70 , 'center_y': .90}
        Add_Carrera:
            text: '[b][color=#000000]DOCENCIA SUPERIOR'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .70,'center_y': .75}
            on_press: 
                root.current=('carreras')
                root.datos('maestria_y_postgrado',"CTF-228-2011,  27-Diciembre-2011   CTF-35-2014,  28 de abril de 2014")
                root.carrera()
        Add_Carrera:
            text: '[b][color=#000000]PEDAGOGIA'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .70,'center_y': .55}
            on_press: 
                root.current=('carreras')
                root.datos('maestria_y_postgrado',"CTF-33-2014 del 28 de abril de 2014")
                root.carrera()              
        Add_Carrera:
            text: '[b][color=#000000]     METODOS ALTERNOS DE \nRESOLUCION DE CONFLICTOS'
            background_color: (255, 255, 255, 0.9)
            pos_hint:{'center_x': .70,'center_y': .65}
            on_press: 
                root.current=('carreras')
                root.datos('maestria_y_postgrado',"CTF-32-2014 del 28 de abril de 2014")
                root.carrera()
        Boton_Atras:  
        	color: (0, 0, 0, 1)
        	background_color: (255, 255, 255, 0.9) 
        	pos_hint:{'center_x': .5,'center_y': .07}       
            on_press: root.current = "principal"    
    Facultades: #Arquitectura 
        name: 'arquitectura'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/Facultad_Arquitectura.png'
        Titulo:
            text:
                ('[b][color=#4e4e4e] FACULTAD DE ARQUITECTURA,\n   COMUNICACION Y DISEÑO[/b]')
            multiline: True
        Add_Carrera:
            text:'[b]LIC. EN ARQUITECTURA'      
            size:(400, 50)
            pos_hint:{'center_x': .5,'center_y': .73}
            on_press: 
                root.current=('carreras')
                root.datos('arquitectura','CTF-173 -2011 / 27-Diciembre-2011')
                root.carrera() 
        Add_Carrera:
            text:'[b]LIC. EN DISEÑO DE INTERIORES[/b]'
            size:(400, 50)
            pos_hint:{'center_x': .5,'center_y': .63}
            on_press: 
                root.current=('carreras')
                root.datos('arquitectura','CTF-17-2014 del 28 de abril de 2014')
                root.carrera() 
        Add_Carrera:
            text:'[b]LIC. EN DISEÑO GRAFICO[/b]'
            size:(400, 50)
            pos_hint:{'center_x': .5,'center_y': .53}
            on_press: 
                root.current=('carreras')
                root.datos('arquitectura','CTF-18-2014 del 28 de abril de 2014')
                root.carrera() 
        Add_Carrera:
            text:'[b]        LIC. EN DISEÑO GRAFICO CON\n ENFASIS EN PUBLICIDAD Y MERCADEO[/b]'
            multiline: True
            size:(400, 50)
            pos_hint:{'center_x': .5,'center_y': .43}
            on_press: 
                root.current=('carreras')
                root.datos('arquitectura','CTF-52 -2013 / 23-Agosto-2013')
                root.carrera() 
        Add_Carrera:
            text:'[b]LIC. EN COMUNICACION AUDIOVISUAL CON\n   ENFASIS EN PRODUCCION DE RADIO Y TV[/b]'
            multiline: True
            size:(400, 50)
            pos_hint:{'center_x': .5,'center_y': .33}    
            on_press: 
                root.current=('carreras')
                root.datos('arquitectura','CTF-65-2013 del 28 de noviembre de 2013')
                root.carrera()   
        Add_Carrera:
            text:'[b]LIC. EN PUBLICIDAD Y MERCADEO CON\n   ENFASIS EN IMAGEN CORPORATIVA[/b]'
            multiline: True
            size:(400, 50)
            pos_hint:{'center_x': .5,'center_y': .23}    
            on_press: 
                root.current=('carreras')
                root.datos('arquitectura',"CTF-135-2012- CTF-116-2011")
                root.carrera()  
        Boton_Atras:
            on_press: root.current = "licenciatura"
        Boton_Siguiente:
            on_press: root.current = "principal"
    Facultades: #Ciencias Admnistrativas
        name: 'cienciasAdministrativas'
        canvas:
        	Rectangle:
            	pos: self.pos
            	size: self.size
            	source: 'data/ciencias_administrativas.jpg'
        Titulo:
            text:
                ('[b][color=#000096]FACULTAD DE CIENCIAS\n    ADMINISTRATIVAS[/b]')
            font_size: 30
            multiline: True
            pos_hint:{'center_x': .5 , 'center_y': .93}
        Add_Carrera:
	        text:('[b]LIC. EN ADMINISTRACION DE NEGOCIOS[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .83} 
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-124-2012 de 12 de noviembre de 2012")
                root.carrera()         
	    Add_Carrera:
	        text:('[b]LIC. EN CONTABILIDAD[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .764}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-127-2012 de 12 de noviembre de 2012")
                root.carrera()  
	    Add_Carrera:
	        text:('[b]LIC. EN ADMINISTRACION DE RECURSOS HUMANOS[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .698}   
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-195-2011 / 27-Diciembre-2011")
                root.carrera()  
	    Add_Carrera:
	        text:('[b]LIC. EN BANCA Y FINANZAS[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .632}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-224-2011 / 27-Diciembre-2011")
                root.carrera()  
	    Add_Carrera:
	        text:('[b]LIC. EN COMERCIO INTERNACIONAL[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .566}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-115-2011 / 27-Diciembre-2011")
                root.carrera()  
	    Add_Carrera:
	        text:('[b]LIC. EN NEGOCIOS INTERNACIONALES[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .50}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-25-2014 del 28 de abril de 2014")
                root.carrera()  
	    Add_Carrera:
	        text:('[b]LIC. EN INGENIERIA COMERCIAL[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .434}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-22-2014 del 28 de abril de 2014")
                root.carrera()  
	    Add_Carrera:
	        text:('[b]LIC. EN COMPORTAMIENTO ORGANIZACIONAL\n                 Y DESARROLLO HUMANO[/b]')
	        multiline: True
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .368}   
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-20-2014 del 28 de abril de 2014")
                root.carrera()  
		Add_Carrera:
	        text:('[b]LIC. EN GLOBAL BUSINESS[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .302}   
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-21-2014 del 28 de abril de 2014")
                root.carrera()  
		Add_Carrera:
	        text:('[b]LIC. EN ADMINISTRACION DE EMPRESAS TURISTICAS[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .236}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-19-2014 del 28 de abril de 2014")
                root.carrera()  
		Add_Carrera:
	        text:('[b]LIC. EN MERCADEO Y PUBLICIDAD[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size_hint:(None, None)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .17}    
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-24-2014 del 28 de abril de 2014")
                root.carrera()  
		Add_Carrera:
	        text:('[b]LIC. EN MERCADEO Y VENTAS[/b]')
	        background_color: (0, 0, 255, 0.5)
	        size:(400, 40)
	        pos_hint:{'center_x': .5,'center_y': .104}   
	        on_press: 
                root.current=('carreras')
                root.datos('cienciasAdministrativas',"CTF-23-2014 del 28 de abril de 2014")
                root.carrera()  
        Boton_Atras:
        	background_color: (0, 0, 255, 0.5)
        	pos_hint:{'center_x': .25,'center_y': .03}
            on_press: root.current = "licenciatura"
        Boton_Siguiente:
        	background_color: (0, 0, 255, 0.5)
        	pos_hint:{'center_x': .75,'center_y': .03}
            on_press: root.current = "principal"
    Facultades: #Salud
        name: 'salud'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/salud.jpg'
        Titulo:
            text:('[b][color=#0101DF]FACULTAD DE CIENCIAS\n           DE LA SALUD[/b]')
            multiline: True
        Add_Carrera:
            text:('[b]DOCTOR EN MEDICINA')
            background_color: (0, 1, 255, 0.8) 
            size:(340, 50)
            on_press: 
                root.current=('carreras')
                root.datos('salud',"CTF-29-2014 del 28 de abril de 2014")
                root.carrera() 
        Add_Carrera:
            text:('[b]DOCTOR EN CIRUGIA DENTAL')
            background_color: (0, 1, 255, 0.8)
            pos_hint:{'center_x': .5,'center_y': .6} 
            size:(340, 50)
            on_press: 
                root.current=('carreras')
                root.datos('salud',"CTF-28-2014 del 28 de abril de 2014")
                root.carrera() 
        Add_Carrera:
            text:('[b]LICENCIATURA EN ENFERMERIA')
            background_color: (0, 1, 255, 0.8)
            pos_hint:{'center_x': .5,'center_y': .5} 
            size:(340, 50)
            on_press: 
                root.current=('carreras')
                root.datos('salud',"CTF-27-2014 del 28 de abril de 2014")
                root.carrera() 
        Add_Carrera:
            text:('[b]LICENCIATURA EN PSICOLOGIA')
            background_color: (0, 1, 255, 0.8)
            pos_hint:{'center_x': .5,'center_y': .4} 
            size:(340, 50)
            on_press: 
                root.current=('carreras')
                root.datos('salud',"CTF-117-2011 / 27-Diciembre-2011")
                root.carrera() 
        Add_Carrera:
            text:('[b]LICENCIATURA EN NUTRICION Y DIETETICA')
            background_color: (0, 1, 255, 0.8)
            pos_hint:{'center_x': .5,'center_y': .3}
            size:(340, 50) 
            on_press: 
                root.current=('carreras')
                root.datos('salud',"CTF-26-2014 del 28 de abril de 2014")
                root.carrera()            
        Boton_Atras:
        	background_color: (0, 1, 255, 0.8)
            on_press: root.current = "licenciatura"
        Boton_Siguiente:
        	background_color: (0, 1, 255, 0.8)
            on_press: root.current = "principal"
    Facultades: #Derecho
        name: 'derecho'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/der.jpg'
        Titulo:
            text:
                ('[b][color=#990000]FACULTAD DE DERECHO[/b]')
        Add_Carrera:
            text:('[b]LIC. EN DERECHO Y CIENCIAS POLITICAS')
            background_color: (1.0, 0, 0, 0.6)
            size:(400, 70)
            pos_hint:{'center_x': .5,'center_y': .65} 
            on_press: 
                root.current=('carreras')
                root.datos('derecho',"CTF-16-2014 del 28 de abril de 2014")
                root.carrera()
        Add_Carrera:
            text:('[b]LIC. EN CRIMINOLOGIA')
            background_color: (1.0, 0, 0, 0.6)
            size:(400, 70)
            pos_hint:{'center_x': .5,'center_y': .45} 
            on_press: 
                root.current=('carreras')
                root.datos('derecho',"CTF-15-2014 del 28 de abril de 2014")
                root.carrera()
        Boton_Atras:
        	background_color: (1.0, 0, 0, 0.6)
        	on_press: root.current = "licenciatura"
        Boton_Siguiente:
        	background_color: (1.0, 0, 0, 0.7)
        	on_press: root.current = "principal"
    Facultades: #Gastronomia
        name: 'gastronomia'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/gastro.jpg'
        Titulo:
            text:('[b][color=#993300]GASTRONOMIA, HOTELERIA Y TURISMO[/b][/color]')
        Add_Carrera:
            text:('[b]LIC. INTERNACIONAL EN ADMINISTRACION\n              DE EMPRESAS HOTELERAS')
            background_color: (1.1, 0, 0, 0.7)
            size:(420, 70)
            pos_hint:{'center_x': .5,'center_y': .70} 
            on_press: 
                root.current=('carreras')
                root.datos('gastronomia',"CTF-14-2011 / 29-Diciembre-2010")
                root.carrera() 
        Add_Carrera:
            text:('[b]LIC. INTERNACIONAL EN ADMINISTRACION\n              DE EMPRESAS TURISTICAS')
            background_color: (1.1, 0, 0, 0.7)
            size:(420, 70)
            pos_hint:{'center_x': .5,'center_y': .55} 
            on_press: 
                root.current=('carreras')
                root.datos('gastronomia',"CTF-15-2011 / 29-Diciembre-2010")
                root.carrera()
        Add_Carrera:
            text:('[b]LIC. INTERNACIONAL EN ARTES CULINARIAS')
            background_color: (1.1, 0, 0, 0.7)
            size:(420, 70)
            pos_hint:{'center_x': .5,'center_y': .40} 
            on_press: 
                root.current=('carreras')
                root.datos('gastronomia',"CTF-120-2011 / 27-Diciembre-2011")
                root.carrera()
        Boton_Atras:
        	background_color: (1.1, 0, 0, 0.7)
        	on_press: root.current = "licenciatura"
        Boton_Siguiente:
        	background_color: (1.1, 0, 0, 0.7)
        	on_press: root.current = "principal"
    Facultades: #Ingenieria y Sistemas
        name: 'ingsistemas'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/ingenieria.jpg'
        Titulo:
            text:('[b][color=#000000]FACULTAD DE INGENIERIA Y SISTEMAS[/b]')
        Add_Carrera:
            text:('[b][color=#000000]  LIC. EN ING. EN REDES Y DATOS CON\nENFASIS EN SISTEMAS INALAMBRICOS')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .8} 
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-25-2011 / 08-Julio-2011")
                root.carrera()        
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. EN SISTEMAS\n    COMPUTACIONALES')
            background_color: (0, 0, 128, 0.5)
            pos_hint:{'center_x': .5,'center_y': .72}
            size:(410, 40)    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas','CACAD-R-03-2009 / 05-Junio')
                root.carrera()
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. EN ELECTRONICA\n       Y COMUNICACIONES')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .64}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-18-2011 / 04-Febrero-2011")
                root.carrera()  
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. INDUSTRIAL CON ENFASIS\n           EN GESTION DE CALIDAD')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .56}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-51-2014 / 20 de mayo de 2014")
                root.carrera()  
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. INDUSTRIAL CON ENFASIS\n        EN GESTION DE OPERACIONES') 
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .48}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-52-2014 / 20 de mayo de 2014")
                root.carrera()  
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. INFORMATICA CON ENFASIS\n         EN DESARROLLO DE SOFTWARE')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .40}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-53-2014 / 20 de mayo de 2014")
                root.carrera()  
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. INFORMATICA CON ENFASIS\n     EN REDES Y SISTEMAS TELEMATICOS')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .32}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-54-2014 / 20 de mayo de 2014")
                root.carrera()  
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. INDUSTRIAL Y DE SISTEMAS')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .24}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CTF-200-2011 / 27-Diciembre-2011")
                root.carrera()  
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN SIST. COMP. CON ENFASIS EN DESARROLLO\n     DE SIST. AVANZADOS DE REDES Y SOFTWARE')
            background_color: (0, 0, 128, 0.5)
            size:(410, 40)
            pos_hint:{'center_x': .5,'center_y': .16}    
            on_press: 
                root.current=('carreras')
                root.datos('ingsistemas',"CACAD-R-04-2009 / 05-Junio-2009")
                root.carrera()  
        Boton_Atras:
        	background_color: (0, 0, 128, 0.5)
        	color: (0, 0, 0, 1)
            on_press: root.current = "licenciatura"
        Boton_Siguiente:
        	background_color: (0, 0, 128, 0.5)
        	color: (0, 0, 0, 1)
            on_press: root.current = "principal"
    Facultades: #Maritima    
        name: 'maritima'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/maritima.jpg'
        Titulo:
            text:('[b][color=#000000]FACULTAD MARITIMA Y PORTUARIA[/b]')
            pos_hint:{'center_x': .5,'center_y': .85}
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ADM. MARITIMA Y PORTUARIA')
            size:(460, 50)
            pos_hint:{'center_x': .5,'center_y': .65} 
            background_color: (255, 255, 255, 1)
            on_press: 
                root.current=('carreras')
                root.datos('maritima',"CTF-14-2013 -  16-Abril-2013")
                root.carrera()
        Add_Carrera:
            text:('[b][color=#000000]      LIC. EN GESTION MARITIMA CON\nENFASIS EN OPERACIONES PORTUARIAS')
            size:(460, 50)
            pos_hint:{'center_x': .5,'center_y': .55} 
            background_color: (255, 255, 255, 1)
            on_press: 
                root.current=('carreras')
                root.datos('maritima',"CTF-51-2013 - 23-Agosto-2013")
                root.carrera()
        Add_Carrera:
            text:('[b][color=#000000]      LIC. EN GESTION MARITIMA CON\nENFASIS EN TRANSPORTE MULTIMODAL')
            size:(460, 50)
            pos_hint:{'center_x': .5,'center_y': .45}
            background_color: (255, 255, 255, 1)
            on_press: 
                root.current=('carreras')
                root.datos('maritima',"CTF-50-2013 - 23-Agosto-2013")
                root.carrera()
        Add_Carrera:
            text:('[b][color=#000000]LIC. EN ING. DE TRANSPORTE Y LOGISTICA')
            size:(460, 50)
            pos_hint:{'center_x': .5,'center_y': .35} 
            background_color: (255, 255, 255, 1)
            on_press: 
                root.current=('carreras')
                root.datos('maritima',"CACAD-R-02-2010  -  5-FEBRERO-2010")
                root.carrera()
        Boton_Atras:
        	background_color: (255, 255, 255, 1)
        	color: (0, 0, 0, 1)
            on_press: root.current = "licenciatura"
        Boton_Siguiente:
        	background_color: (255, 255, 255, 1)
        	color: (0, 0, 0, 1)
            on_press: root.current = "principal"
    Maestrias: #Empresariales
        name: 'empresarialesmaestria'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                # source: 'data/maestria-adm-negocios-finanzas.jpg'
                source: 'data/Empresariales.jpg'
        Titulo:
            text:
                ('[b][color=#000000]EMPRESARIALES[/b]')
        Add_Carrera:
            text:'[b][color=#000000]   MAESTRIA EN ADMINISTRACION DE\n NEGOCIOS CON ENFASIS EN FINANZAS'
            multiline: True
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .78}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF-48-2013 del 23 de agosto de 2013")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]   MAESTRIA EN ADMINISTRACION DE\n NEGOCIOS CON ENFASIS EN MERCADEO'
            multiline: True
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .68}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF-49-2013 del 23 de agosto de 2013")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]    MAESTRIA EN ADMINISTRACION DE NEGOCIOS CON\n ENFASIS EN ESPECIALIZACION EN RECURSOS HUMANOS'
            multiline: True
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .58}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF-155-2012")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN ADMINISTRACION DE NEGOCIOS\n   CON ENFASIS EN GERENCIA ESTRATEGICA'
            multiline: True
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .48}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF - 129-2012")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN ADMINISTRACION DE NEGOCIOS\n CON ENFASIS EN COMERCIO INTERNACIONAL'
            multiline: True
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .38}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF-132-2012")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN CONTABILIDAD CON ENFASIS\n     EN GESTION TRIBUTARIA Y FISCAL'
            multiline: True
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .28}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF-44-2013 del 23 de agosto de 2013")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN ADMINISTRACION HOTELERA'
            size:(410, 50)
            background_color: (255, 255, 0, 0.8)
            pos_hint:{'center_x': .5,'center_y': .18}
            on_press: 
                root.current=('carreras')
                root.datos('empresarialesmaestria',"CTF-134-2012 del 12 de Noviembre de 2012")
                root.carrera()
        Boton_Atras:
        	color: (0, 0, 0, 1)
        	background_color: (255, 255, 0, 0.8)
            on_press: root.current = "maestria_y_postgrado"
        Boton_Siguiente:
        	color: (0, 0, 0, 1)
        	background_color: (255, 255, 0, 0.8)
            on_press: root.current = "principal"
    Maestrias: #Innovacion
        name: 'innovacionmaestria'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source:'data/Innovacion.jpg'
        Titulo:
            text:
                ('[b][color=#cc00cc]INNOVACION Y LOGISTICA[/b]')
        Add_Carrera:
            text:'[b]MAESTRIA EN GESTION AMBIENTAL'
            background_color: (1, 0, 1, 0.8)
            size:(350, 70)
            pos_hint:{'center_x': .5,'center_y': .70}
            on_press: 
                root.current=('carreras')
                root.datos('innovacionmaestria',"CTF-45-2014 del 28 de abril de 2014")
                root.carrera()
        Add_Carrera:
            text:'[b]MAESTRIA EN GESTION LOGISTICA\n  DEL TRANSPORTE MULTIMODAL'
            background_color: (255/255, 153/255, 255/255, 0.8)
            multiline: True
            size:(350, 70)
            pos_hint:{'center_x': .5,'center_y': .55}
            on_press: 
                root.current=('carreras')
                root.datos('innovacionmaestria',"CTF-46-2014 del 28 de abril de 2014")
                root.carrera()
		Add_Carrera:
            text:'[b]MAESTRIA EN GERENCIA DEL\n TRANSPORTE MULTIMODAL'
            background_color: (1, 0, 1, 0.8)
            multiline: True
            size:(350, 70)
            pos_hint:{'center_x': .5,'center_y': .40}
            on_press: 
                root.current=('carreras')
                root.datos('innovacionmaestria',"CTF - 131-2012  -  12-Noviembre-2012")
                root.carrera()
        Add_Carrera:
            text:'[b]MAESTRIA EN GERENCIA DE PROYECTOS'
            background_color: (1, 0, 1, 0.8)
            size:(350, 70)
            pos_hint:{'center_x': .5,'center_y': .25}
            on_press: 
                root.current=('carreras')
                root.datos('innovacionmaestria',"CTF - 154-2012  -  04-Diciembre-2012")
                root.carrera()
        Boton_Atras:
        	background_color: (1, 0, 1, 0.8)
            on_press: root.current = "maestria_y_postgrado"
        Boton_Siguiente:
        	background_color: (1, 0, 1, 0.8)
            on_press: root.current = "principal"
    Maestrias: #Educacion
        name: 'educacionmaestria'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/Educacion.jpg'
        Titulo:
            text:
                ('[b][color=#993300]EDUCACION[/b]')
            pos_hint:{'center_x': .5,'center_y': .80}
        Add_Carrera:
            text:'[b]         MAESTRIA EN EDUCACION CON\n ESPECIALIZACION EN DOCENCIA SUPERIOR'
            background_color: (1.1, 0, 0, 0.7)
            multiline: True
            size:(400, 70)
            pos_hint:{'center_x': .5,'center_y': .60}
            on_press: 
                root.current=('carreras')
                root.datos('educacionmaestria',"CTF-36-2014 del 28 de abril de 2014")
                root.carrera()
        Add_Carrera:
            text:'[b]      MAESTRIA EN EDUCACION CON\n ESPECIALIZACION EN PSICOPEDAGOGIA'
            background_color: (1.1, 0, 0, 0.7)
            multiline: True
            size:(400, 70)
            pos_hint:{'center_x': .5,'center_y': .45}
            on_press: 
                root.current=('carreras')
                root.datos('educacionmaestria',"CTF-125-2012,  12-Noviembre-2012")
                root.carrera()
        Boton_Atras:
        	background_color: (1.1, 0, 0, 0.7)
            on_press: root.current = "maestria_y_postgrado"
        Boton_Siguiente:
        	background_color: (1.1, 0, 0, 0.7)
            on_press: root.current = "principal"
    Maestrias: #Derecho 
    	name: 'derechomaestria'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/derecho.jpg'
        Titulo:
            text:
                ('[b][color=#990000]DERECHO[/b]')
        Add_Carrera:
            text:'[b]MAESTRIA EN DERECHO COMERCIAL'
            background_color: (1.0, 0, 0, 0.8)
            size:(420, 50)
            on_press: 
                root.current=('carreras')
                root.datos('derechomaestria',"CTF-08-2013 - 29-Enero-2013")
                root.carrera()
        Add_Carrera:
            text:'[b]MAESTRIA EN DERECHO PROCESAL'
            background_color: (1.0, 0, 0, 0.8)
            size:(420, 50)
            pos_hint:{'center_x': .5,'center_y': .6}
            on_press: 
                root.current=('carreras')
                root.datos('derechomaestria',"CTF-118-2011  -  27-Diciembre-2011")
                root.carrera()
        Add_Carrera:
            text:'[b]MAESTRIA EN MEDIACION, NEGOCIACION Y ARBITRAJE'
            background_color: (1.0, 0, 0, 0.8)
            size:(420, 50)
            pos_hint:{'center_x': .5,'center_y': .5}
            on_press: 
                root.current=('carreras')
                root.datos('derechomaestria',"Proximamente")
                root.carrera()
        Add_Carrera:
            text:'[b]MAESTRIA EN DERECHO CIVIL Y PENAL'
            background_color: (1.0, 0, 0, 0.8)
            size:(420, 50)
            pos_hint:{'center_x': .5,'center_y': .4}
            on_press: 
                root.current=('carreras')
                root.datos('derechomaestria',"CTF-118-2011 del 27 de diciembre de 2011")
                root.carrera()
        Boton_Atras:
        	background_color: (1.0, 0, 0, 0.8)
            on_press: root.current = "maestria_y_postgrado"
        Boton_Siguiente:
        	background_color: (1.0, 0, 0, 0.8)
            on_press: root.current = "principal"
    Maestrias: #Sistemas de Info
        name: 'sistemaimaestria'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source:'data/sistema_informacion.jpg'
        Titulo:
            text:
                ('[b]SISTEMA DE INFORMACION[/b]')
            pos_hint:{'center_x': .5,'center_y': .80}
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN GERENCIA DE SISTEMAS CON\n   ENFASIS EN SEGURIDAD INFORMATICA'
            multiline: True
            background_color: (0, 50, 128, 1)
            size:(350, 50)
            pos_hint:{'center_x': .5,'center_y': .55}
            on_press: 
                root.current=('carreras')
                root.datos('sistemaimaestria',"CTF-47 -2013 del 23 de agosto de 2013")
                root.carrera()
        Boton_Atras:
        	color: (0, 0, 0, 1)
        	background_color: (0, 50, 128, 1)
            on_press: root.current = "maestria_y_postgrado"
        Boton_Siguiente:
        	color: (0, 0, 0, 1)
        	background_color: (0, 50, 128, 1)
            on_press: root.current = "principal"
    Maestrias: #Salud
        name: 'saludmaestria'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/servicio-salud.jpg'
        Titulo:
            text:
                ('[b][color=#66cc00]SALUD[/b]')
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN ORTODONCIA'
            background_color: (0, 128, 0, 0.7)
            size_hint:(None, None)
            size:(350, 50)
            pos_hint:{'center_x': .5,'center_y': .60}
            on_press: 
                root.current=('carreras')
                root.datos('saludmaestria',"CTF-35-2014 del 28 de abril de 2014")
                root.carrera()
        Add_Carrera:
            text:'[b][color=#000000]MAESTRIA EN ADMINISTRACION DE\n    LOS SERVICIOS DE LA SALUD'
            background_color: (0, 128, 0, 0.7)
            multiline: True
            size:(350, 50)
            pos_hint:{'center_x': .5,'center_y': .50}
            on_press: 
                root.current=('carreras')
                root.datos('saludmaestria',"CTF-70-2013")
                root.carrera()
        Boton_Atras:
        	color: (0, 0, 0, 1)
        	background_color: (0, 128, 0, 0.7)
            on_press: root.current = "maestria_y_postgrado"
        Boton_Siguiente:
        	color: (0, 0, 0, 1)
        	background_color: (0, 128, 0, 0.7)
            on_press: root.current = "principal"
    Carreras: 
        name: 'carreras'
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'data/fondo_azul.jpeg'
        Titulo:
            text:('[b][/b]'+root.titulo)
            # font_name: 'snap____.ttf'
            font_size: 20
            size_hint:(None, None)
            size:(100, 44)
        TextoInfo:        
            text: 'Resolucion: '      
        ResultadoInfo:
            text: u" "+root.resolucion            
        TextoInfo:
            text: 'Duración: ' 
            pos_hint:{'right_top': .10,'center_y': .65}
        ResultadoInfo:
            text: " "+root.duracion
            pos_hint:{'center_x': .60,'center_y': .65}
            disabled: True
        TextoInfo:
            text: 'Sede: ' 
            pos_hint:{'right_top': .10,'center_y': .55}
        ResultadoInfo:
            text: " "+root.sede
            pos_hint:{'center_x': .60,'center_y': .55}
        TextoInfo:
            text: 'Horario: ' 
            pos_hint:{'right_top': .10,'center_y': .45}
        ResultadoInfo:
            text: " "+root.horario
            pos_hint:{'center_x': .60,'center_y': .45} 
        TextoInfo:
            text: 'Modalidad: ' 
            pos_hint:{'right_top': .10,'center_y': .35}
        ResultadoInfo:
            text: " "+root.modalidad
            pos_hint:{'center_x': .60,'center_y': .35} 
        Boton_Atras:
            on_press: 
                root.current= ''+root.nombreVentana
                root.limpiar()
        #Boton De PLan de Estudios
        Boton_Atras:
            text: 'Requisitos'
            size:(150, 30)
            pos_hint:{'center_x': .5,'center_y': .25}
            on_press:  
                root.carrera() 
                root.current='requisitos' 
        Boton_Siguiente:
            text: 'Plan de Estudio'
            size:(150, 30)
            pos_hint:{'center_x': .5,'center_y': .18}
            on_press:  
                root.carrera() 
                root.current='planEstudio' 
        Boton_Siguiente:
            text: 'Menu Principal'            
            on_press: 
                root.current = "principal"
                root.limpiar()
        # PlanDeEstudio:
        #     name:"planestudio" 
    PlanDeEstudio:
        name: 'requisitos'
        Widget: 
            Scatter:
                size_hint: None, None
                size: image.size
                Plan:
                    id: image
                    #source: 'data/plan/'+root.requerimiento
                    source: 'http://faru.noip.me/data/plan/'+root.requerimiento
        Boton_Atras:
            on_press:  root.current = "carreras"
    PlanDeEstudio:
        name: 'planEstudio'
        canvas:
            Color:
                rgb: (.9, .9, .9)
            Rectangle:
                pos: self.pos
                size: self.size
        Widget: 
            Scatter:
                size_hint: None, None
                size: image.size
                Plan:
                    id: image
                    #source: 'data/plan/'+root.plan
                    source: 'http://faru.noip.me/data/plan/'+root.plan
        Boton_Atras:
            on_press:  root.current = "carreras"